name: AI Code Review for PRs

on:
  pull_request:
    paths:
      - "**/*.cls"
      - "**/*.trigger"
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  ai_review:
    name: IA Review en Apex con OpenAI
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para obtener diffs

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🔍 Ejecutar revisión IA de PR
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        run: node scripts/review-pr.js
