name: AI Code Review for PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_review:
    name: Revisi칩n Inteligente con IA
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Clonar repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para obtener diffs

      - name: 游릭 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 游닍 Instalar dependencias
        run: npm install

      - name: 游댌 Ejecutar revisi칩n IA de PR
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/review-pr.js
